version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hunty
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: